### ISSUE TITLE
style.css isn't correct

### ISSUE THREAD

**Issue by rfparedes** [schollz/onetwothree#1]
I had to pull the style.css from here:
wget https://schollz.github.io/onetwothree/css/style.css

The one on github styles page totally different than your demo site.

**Comment by schollz** [comment]
@rfparedes Sorry about that. I was playing with different styles. The original style (on the demo) is now default. You can change the style by adding `style="2/3"` in the config.

**Comment by rfparedes** [comment]
Yes, thanks. It's your theme for your site so you should be able to do what
you want with it. :)
