### ISSUE TITLE
example site

### ISSUE THREAD

**Issue by karakays** [schollz/onetwothree#3]
Is there an example site that shows the usage, available parameters and config.toml etc. look like?

**Comment by schollz** [comment]
Yes, I use it for my [blog](https://schollz.github.io/), [see source](https://github.com/schollz/schollz.github.io/tree/source).

There are three styles available and my blog uses [style 3](https://github.com/schollz/schollz.github.io/blob/source/config.toml#L16). The style shown for this theme is the default style.
